### ISSUE TITLE
Component default params value configuration

### ISSUE THREAD

**Issue by netcitylife** [pinterweb/aurelia-fontawesome#11]
**I'm submitting a feature request**

* **Library Version:**
0.2.0

* **Browser:**
all

**Current behavior:**
All component properties have non-configurable default values

**What is the expected behavior?**
It is possible to override default values via plugin configuration.

**What is the motivation / use case for changing the behavior?**
For example I want all icons to have fixed width, so I should be able to set fixedWidth default value via plugin configuration. It would also be great to create a configurable array of icons, which would be automatically registered in FA library, so developer would not have to register them by himself. He would then need just to import them and pass wo configuration option:

```javascript
import { fab } from '@fortawesome/free-brands-svg-icons'
import { faCheckSquare, faCoffee } from '@fortawesome/free-solid-svg-icons'

export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .plugin(PLATFORM.moduleName('aurelia-fontawesome', config => {
      config.registerIcons([fab, faCheckSquare, faCoffee])
      config.options.fixedWith = true;
    }));

  // other code ...

  return aurelia.start().then(() => aurelia.setRoot(PLATFORM.moduleName('app')));
}
```

**Comment by jmzagorski** [comment]
I think this is a good idea. I will work on https://github.com/jmzagorski/aurelia-fontawesome/issues/12 first and if you have time to submit a PR for this one please feel free and let me know. If not, I will message you back when I am ready to work on it.

**Comment by netcitylife** [comment]
I do not have enough experience in plugin development, so i might miss some procedural things or make them the wrong way for the first time. So i would be glad if you do it for now.

**Comment by jmzagorski** [comment]
Okay that's fine. When I can get to this I will create a PR for you to look over.

**Comment by jmzagorski** [comment]
@netcitylife In the meantime if you are using webpack you can use [aurelia-fontawesome-loader](https://github.com/rmja/aurelia-fontawesome-loader) to autoload your icons. I have not tried it out yet, but it looks promising.

**Comment by jmzagorski** [comment]
I did not forget you @netcitylife, i am trying to finish up a work project and then I plan on adding this feature.

**Comment by netcitylife** [comment]
That's not a problem, thank you very much for your work and attention.

**Comment by netcitylife** [comment]
Did you decide anything about moving plugin to official fontawesome repo?

**Comment by jmzagorski** [comment]
They told me to open a feature request since one of the maintainers said:

> we are building official components for the most used frameworks

Here it is: https://github.com/FortAwesome/Font-Awesome/issues/14822, although it is unlikely for them to respond soon given their number of issues.

**Comment by netcitylife** [comment]
Hi. What about this feature?

**Comment by jmzagorski** [comment]
Hi, sorry for the delay. I just finished a huge project at work so I will have time to add this to my backlog to work on in the next few weeks. Hopefully sooner than later, but I will release a new version when finished.

**Comment by jmzagorski** [comment]
@netcitylife What is your expectation if you change a default value and icons are already rendered? For example you change the `fixedWidth` from true to false? Should all icons re-render on the screen based on your change, or should only future icons use that new default value or should nothing happen?

**Comment by netcitylife** [comment]
Icon settings are applied at application configuration step, thus there are no icons rendered at that time (is most cases). If somebody wants to apply default settings to already rendered icons (a very rare case), i think he should make it himself, via BindingSignaler, for example.

**Comment by jmzagorski** [comment]
okay thank you, and I think that is a good start without over designing this feature since the `@bindable` is made to handle changes. I've started work on this feature and have some other "chore" items to do before releasing 1.0. See #18

**Comment by jmzagorski** [comment]
@netcitylife i started working on this, but from a different viewpoint internally. You can pull down and run the dev-app from the features/plugin-configuration branch with `npm start`. 

The concept is the same, you pass in an object that has `iconOptions` (which is just all the `bindable` properties) and an array of `IconDefinitions` or `IconPack`:

```typescript
  aurelia.use
    .standardConfiguration()
    .plugin('aurelia-fontawesome', {
      iconOptions: yourIconOptions,
      icons: [ faCircle, faHome, faSpinner ]
    });
```

Right now I hold onto the `iconOptions` object, so if any value on that interface changes after aurelia starts it will affect any new icons that get added to the dom after aurelia has started. I demonstrate this by changing the `spin` property every 5 seconds and allowing you to dynamically add an icon in the dev app, so if you click the button and spin is false all those added icons will not spin. Let me know what you think or if you have questions.

**Comment by jmzagorski** [comment]
@netcitylife The pull request for your feature is available. Would you be able to take a look at it either by running the dev-app on the branch or install the branch in of your apps? To install in your app you can run:

`npm i -S pinterweb/aurelia-fontawesome#features/plugin-configuration`

**Comment by netcitylife** [comment]
Hi, sorry for the late response, I am very busy now (
I'll check it soon, thanks

**Comment by jmzagorski** [comment]
No worries. I merged the change into master so you can look at that branch. I will not publish to NPM until the check list is done in https://github.com/pinterweb/aurelia-fontawesome/issues/18. I am currently working on "Adding binding property for prefix" in my https://github.com/pinterweb/aurelia-fontawesome/tree/features/prefix_config branch
