### ISSUE TITLE
Why do only brand icons require a 'fab' prefix but regular do not require 'far'?

### ISSUE THREAD

**Issue by lebolo** [pinterweb/aurelia-fontawesome#20]
**I'm asking a question**

* **Library Version:**
0.2.2

* **Browser:**
Chrome 77.0.3865.90 (Official Build) (64-bit)

I'm using Aurelia w/ Webpack and have set up _aurelia-fontawesome-loader_ and _aurelia-fontawesome_. Everything is working, but was curious why some icons required a prefix, others required a lack of prefix, and some are optional.

For example, the commented out elements give errors because of prefixes.

```html
<!--<font-awesome-icon icon="android"></font-awesome-icon>-->
<font-awesome-icon icon="grin-tongue-wink"></font-awesome-icon>
<font-awesome-icon icon="globe"></font-awesome-icon>

<font-awesome-icon icon.bind="['fab', 'android']"></font-awesome-icon>
<!--<font-awesome-icon icon.bind="['far', 'grin-tongue-wink']"></font-awesome-icon>-->
<font-awesome-icon icon.bind="['fas', 'globe']"></font-awesome-icon>
```

**Comment by jmzagorski** [comment]
The underlying font awesome library needs a prefix when creating the icon. However, this aurelia library defaults to `fas` [here](https://github.com/pinterweb/aurelia-fontawesome/blob/master/src/font-awesome-icon.ts#L35) so you do not need to provide a prefix. That entire `normalizeIconArgs` function shows you the different types you can bind to the `icon` property (string, array, IconDefinition object)

I am [slowly] working on version 1.0, so any enhancement recommendations are welcomed. The big change for 1.0 is global defaults for the custom element. (e.g. I could add a global default prefix, then you do not have to bind the prefix if you are only using fab), or i could inspect all the icons being passed in and if all have a `fab` prefix, set if or you? That would need more discussion though.

**Comment by lebolo** [comment]
Thanks @jmzagorski. I'm still a little confused, why does this work

```html
<font-awesome-icon icon="grin-tongue-wink"></font-awesome-icon>
```

but not

```html
<font-awesome-icon icon.bind="['far', 'grin-tongue-wink']"></font-awesome-icon>
```

[The icon is under the Regular group / prefix](https://fontawesome.com/icons/grin-tongue-wink?style=regular).

All in all, I'm not really making a feature request. I think, once I know the rules, it's perfectly fine to use an explicitly prefix or not. Mainly just curious so I can know what to do without getting an error first.

Thanks for this plugin, btw!

**Comment by jmzagorski** [comment]
I would need more details on which icon set you are loading and how you are loading it (e.g. from your main.ts). Your first example will work if you loaded that icon from the `@fortawesome/free-solid-svg-icons`. if you are not importing `@fortawesome/free-regular-svg-icons` and loading the `grin-tongue-wink` from that import then your second example will not work.

**Comment by lebolo** [comment]
Oh, I'm using I [aurelia-fontawesome-loader](https://github.com/rmja/aurelia-fontawesome-loader). I `npm install`ed `@fortawesome/free-brands-svg-icons`, `@fortawesome/free-regular-svg-icons`, and `@fortawesome/free-solid-svg-icons` and my *main.ts* looks like

```TypeScript
import {Aurelia} from 'aurelia-framework';
import * as environment from '../config/environment.json';
import {PLATFORM} from 'aurelia-pal';
import 'bootstrap';

export function configure(aurelia: Aurelia) {
  aurelia.use
         .standardConfiguration()
         .feature(PLATFORM.moduleName('resources/index'));

  aurelia.use.developmentLogging(environment.debug ? 'debug' : 'warn');

  aurelia.use
         .plugin(PLATFORM.moduleName('aurelia-fontawesome'))
         .plugin(PLATFORM.moduleName('aurelia-fontawesome-loader'));

  if (environment.testing) {
    aurelia.use.plugin(PLATFORM.moduleName('aurelia-testing'));
  }

  aurelia.start().then(() => aurelia.setRoot(PLATFORM.moduleName('app')));
}
```

**Comment by jmzagorski** [comment]
try your example without aurelia-fontawesome-loader, using the explicit `library.add` in your main.ts as explained in the docs. If that works then you may want to open an issue with the loader library.

```typescript
import { library } from '@fortawesome/fontawesome-svg-core'
import {  faGrinTongueWink as fasGTW } from '@fortawesome/free-solid-svg-icons';
import { faGrinTongueWink  } from '@fortawesome/free-regular-svg-icons'

library.add(faGrinTongueWink  , fasGTW )

export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .plugin(PLATFORM.moduleName('aurelia-fontawesome'));

  // other code ...

  return aurelia.start().then(() => aurelia.setRoot(PLATFORM.moduleName('app')));
}
```

**Comment by lebolo** [comment]
Thanks, I'll give it a shot and follow up with them.
